name: geminilocal
description: "Local AI, on-device client"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dynamic_color: ^1.6.9
  shared_preferences: ^2.5.3
  http: ^0.13.3
  flutter_markdown: 0.7.7+1
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.2
  share_plus: 12.0.1
  intl: ^0.20.2
  pubspec_yaml: ^3.1.0
  package_info_plus: ^4.0.2
  collection: ^1.17.0
  fluttertoast: ^8.1.1
  connectivity_plus: ^6.0.1
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/languages.json
    - assets/translations/uk.json
    - assets/translations/en.json
    - assets/translations/zh_TW.json
    - assets/system_prompt.txt
    - assets/additional_resources.json